### PR TITLE
Don't use title overrides if some are missing

### PR DESCRIPTION
**Pull request by karenc**
Need tests

### CODE REVIEW

**Comment by karenc** [comment]
Need more tests.

**Comment by reedstrm** [comment]
I think this is probably wrong. We _should_ break in this case. Any objections to closing this?

**Comment by karenc** [comment]
Does it mean we don't need to handle this case? Just close this and delete the branch?

**Comment by reedstrm** [comment]
Hmm, looking at the actual code, I think perhaps detect the mismatch and error appropriately, rather than throwing a mysterious IndexError from the loop.

**Comment by karenc** [comment]
@reedstrm do you plan to add tests?

**Comment by reedstrm** [comment]
Test added, and it seems to be passing. Yay!

**Comment by karenc** [comment]
Test looks good, thanks!  Do you mind squashing the first 3 commits?

**Pull request merged**
