### PR TITLE
make styles in single-html optional

### PR DESCRIPTION
**Pull request by reedstrm**
Helen's been editing these out, anyway.

### CODE REVIEW

**Comment by pumazi** [comment]
Removing the style altogether would probably be good. It's not really in the scope of the package to worry about style, no?

**Comment by karenc** [comment]
I included the styles because it was in the original script that generates the single html in the cte repository.  I think it'd be better to remove them if Helene doesn't use them.

**Comment by reedstrm** [comment]
I did have a thought of making it a variable that let's you point at a file of styles to incorporate, default none?

**Comment by karenc** [comment]
Let's make it simpler and just remove the styles :D

**Comment by reedstrm** [comment]
o.k. Could one of you do that, as you may have heard my laptop just died, and I don't have a handy copy of my ssh key ... (yikes!)

**Comment by karenc** [comment]
Yes, I'll do that

**Comment by karenc** [comment]
Remove styles in single html #76

**Pull request closed without merging**
