### PR TITLE
Get the title overrides from TOC when adapting single html

### PR DESCRIPTION
**Pull request by karenc**
Depends on https://github.com/Connexions/cnx-easybake/pull/15

### CODE REVIEW

**Comment by reedstrm** [comment]
I note that this used to run off the end of the list. Does it depend on the struture of the incoming HTML at all> i.e. is is possible to cause that same error by writing a bad ruleset-transform?

**Comment by karenc** [comment]
If the table of contents is not updated, we will have that index error again...  Perhaps I should change this to be more robust.

**Comment by reedstrm** [comment]
Yeah, if it falls off the end, perhaps set it to something slightly generic '(untitled)' or something?
(we block that specific string in legacy from being published, BTW)

**Comment by karenc** [comment]
If the table of contents is not the same length as the number of pages in the book, should it just not use title overrides?

**Comment by karenc** [comment]
There's a possibility that we have a composite page in the middle of the book and if we just add "(untitled)" to the pages at the end of the book, the title overrides might be shifted by one?

**Comment by reedstrm** [comment]
Yes, that's true - it will happen, we're adding pages at the end of each chapter. You're right, if we error, we should back out of the whole thing.

**Pull request merged**
